### ISSUE TITLE
deposit in to platform

### ISSUE THREAD

**Issue by 0xsuren** [bifrost-platform/BIFI#2]
i deployed contracts in fork from mainnet and use this code's to make deposit ,  

i use this code's in my test file to make deposit in deployed contracts , 

      await DAIERC20Contract.approve(
        tokenProxyContract.address,
        hre.ethers.utils.parseEther("100")
      );
      const depositTX = await tokenProxyContract.deposit(
        hre.ethers.utils.parseEther("100"),
        false
      );
      await depositTX.wait();

but i get error from  _applyInterest(userAddr); in tokenHandler deposit function , because when i make it comment , deposit is ok .
and when i pass flag as true , deposit work ! 

my deployment is :

const hre = require("hardhat");
const { expect } = require("chai");

describe("", async () => {
  let DAIOracleContract;
  let oracleProxyContract;
  let DAItokenSIContract;
  let DAIERC20Contract;
  let BIFIERC20Contract;

  let managerDataStorageContract;
  let etherManagerContract;
  let etherLiquidationManagerContract;
  let marketHandlerDataStorageContract;
  let interestModelContract;

  let tokenProxyContract;
  let DAImarketSIHandlerDataStorageContract;
  let DAItokenHandlerContract;

  let callProxyContract;

  let owner;

  describe("BiFiX Deploy And Test", function () {
    it("deploy contracts", async function () {
      [owner] = await hre.ethers.getSigners();

      // deploy dai oracle
      const observerOracle = await hre.ethers.getContractFactory(
        "observerOracle"
      );
      DAIOracleContract = await observerOracle.deploy(100000000);
      await DAIOracleContract.deployed();
      console.log("DAIOracleContract deployed to:", DAIOracleContract.address);

      // deploy oracle proxy
      const oracleProxy = await hre.ethers.getContractFactory("oracleProxy");
      oracleProxyContract = await oracleProxy.deploy(DAIOracleContract.address);
      await oracleProxyContract.deployed();
      console.log(
        "oracleProxyContract deployed to:",
        oracleProxyContract.address
      );

      // deploy daiSI from contracts/marketHandler/tokenSI.sol
      const tokenSI = await hre.ethers.getContractFactory("tokenSI");
      DAItokenSIContract = await tokenSI.deploy();
      await DAItokenSIContract.deployed();
      console.log(
        "DAItokenSIContract deployed to:",
        DAItokenSIContract.address
      );

      // deploy erc20 dai from /tokenStandard/openzeppelinERC20.sol
      const DAIERC20 = await hre.ethers.getContractFactory(
        "openzeppelinERC20dai"
      );
      DAIERC20Contract = await DAIERC20.deploy("dai", "DAI", 18);
      await DAIERC20Contract.deployed();
      console.log("DAIERC20Contract deployed to:", DAIERC20Contract.address);

      // deploy erc20 BIFI from /tokenStandard/openzeppelinERC20.sol
      const BIFIERC20 = await hre.ethers.getContractFactory(
        "openzeppelinERC20"
      );
      BIFIERC20Contract = await BIFIERC20.deploy("BIFI", "BIFI", 18);
      await BIFIERC20Contract.deployed();
      console.log("BIFIERC20Contract deployed to:", BIFIERC20Contract.address);

      // deploy ManagerDataStorage from contracts/marketManager/managerDataStorage/managerDataStorage.sol
      const managerDataStorage = await hre.ethers.getContractFactory(
        "managerDataStorage"
      );
      managerDataStorageContract = await managerDataStorage.deploy();
      await managerDataStorageContract.deployed();
      console.log(
        "managerDataStorageContract deployed to:",
        managerDataStorageContract.address
      );

      // deploy Token manager or manager from contracts/marketManager/tokenManager.sol
      const etherManager = await hre.ethers.getContractFactory("etherManager");
      etherManagerContract = await etherManager.deploy(
        managerDataStorageContract.address,
        oracleProxyContract.address,
        "0x6d3A0d57Aa65fe133802c48F659521F7693fa477",
        BIFIERC20Contract.address
      );
      await etherManagerContract.deployed();
      console.log(
        "etherManagerContract deployed to:",
        etherManagerContract.address
      );

      // change manager address in managerDataStorage
      await managerDataStorageContract.setManagerAddr(
        etherManagerContract.address
      );

      // transfer 1000000000 BIFI to etherManagerContract
      await BIFIERC20Contract.transfer(
        etherManagerContract.address,
        hre.ethers.utils.parseEther("1000000000")
      );

      // transfer 1000000000 DAI to user
      await DAIERC20Contract.transfer(
        owner.address,
        hre.ethers.utils.parseEther("1000")
      );

      // deploy etherLiquidationManager from /contracts/marketManager/liquidationManager.sol
      const etherLiquidationManager = await hre.ethers.getContractFactory(
        "etherLiquidationManager"
      );
      etherLiquidationManagerContract = await etherLiquidationManager.deploy(
        etherManagerContract.address
      );
      await etherLiquidationManagerContract.deployed();
      console.log(
        "etherLiquidationManagerContract deployed to:",
        etherLiquidationManagerContract.address
      );

      // set etherLiquidationManager address in etherManagerContract
      await etherManagerContract.setLiquidationManager(
        etherLiquidationManagerContract.address
      );

      // MarketHandlerDataStorage
      const borrowLimit = hre.ethers.utils.parseEther("0.75");
      const martinCallLimit = hre.ethers.utils.parseEther("0.93");
      const minimumInterestRate = 0;
      const liquiditySensitive = hre.ethers.utils.parseEther("0.05");

      const marketHandlerDataStorage = await hre.ethers.getContractFactory(
        "marketHandlerDataStorage"
      );
      marketHandlerDataStorageContract = await marketHandlerDataStorage.deploy(
        borrowLimit,
        martinCallLimit,
        minimumInterestRate,
        liquiditySensitive
      );
      await marketHandlerDataStorageContract.deployed();
      console.log(
        "marketHandlerDataStorageContract deployed to:",
        marketHandlerDataStorageContract.address
      );

      // interestModel
      const interestModel = await hre.ethers.getContractFactory(
        "interestModel"
      );
      interestModelContract = await interestModel.deploy(
        hre.ethers.utils.parseEther("0.025"),
        hre.ethers.utils.parseEther("0.8"),
        hre.ethers.utils.parseEther("0.1"),
        hre.ethers.utils.parseEther("0.18"),
        hre.ethers.utils.parseEther("0.825")
      );
      await interestModelContract.deployed();
      console.log(
        "interestModelContract deployed to:",
        interestModelContract.address
      );

      // handlerProxy
      const tokenProxy = await hre.ethers.getContractFactory("tokenProxy");
      tokenProxyContract = await tokenProxy.deploy();
      await tokenProxyContract.deployed();
      console.log(
        "tokenProxyContract deployed to:",
        tokenProxyContract.address
      );

      // DAI si DataStorage
      const marketSIHandlerDataStorage = await hre.ethers.getContractFactory(
        "marketSIHandlerDataStorage"
      );
      DAImarketSIHandlerDataStorageContract =
        await marketSIHandlerDataStorage.deploy(tokenProxyContract.address);
      await DAImarketSIHandlerDataStorageContract.deployed();
      console.log(
        "DAImarketSIHandlerDataStorageContract deployed to:",
        DAImarketSIHandlerDataStorageContract.address
      );

      // DAI Handler
      const tokenHandler = await hre.ethers.getContractFactory("tokenHandler");
      DAItokenHandlerContract = await tokenHandler.deploy();
      await DAItokenHandlerContract.deployed();
      console.log(
        "DAItokenHandlerContract deployed to:",
        DAItokenHandlerContract.address
      );

      // const daiBorrowLimit = hre.ethers.utils.parseEther("0.75");
      await etherManagerContract.handlerRegister(2, tokenProxyContract.address);
      await marketHandlerDataStorageContract.setTokenHandler(
        tokenProxyContract.address,
        interestModelContract.address
      );
      await tokenProxyContract.initialize(
        2,
        DAItokenHandlerContract.address,
        etherManagerContract.address,
        interestModelContract.address,
        marketHandlerDataStorageContract.address,
        DAIERC20Contract.address,
        "DAI",
        DAItokenSIContract.address,
        DAImarketSIHandlerDataStorageContract.address
      );

      await marketHandlerDataStorageContract.setLimitOfAction(
        hre.ethers.utils.parseEther("100000")
      );
      await marketHandlerDataStorageContract.setLiquidityLimit(
        hre.ethers.utils.parseEther("1")
      );

      const ABI = [
        "function setUnderlyingTokenDecimal(uint256 _underlyingTokenDecimal)",
      ];
      const iface = new hre.ethers.utils.Interface(ABI);
      const callBytes = iface.encodeFunctionData("setUnderlyingTokenDecimal", [
        (10 ** 18).toString(),
      ]);

      await tokenProxyContract.handlerViewProxy(callBytes);

      // CallProxy
      const callProxy = await hre.ethers.getContractFactory(
        "callProxyManagerCallProxyHandlerCallProxyMarketCallProxyUserCallProxySISafeMath"
      );
      callProxyContract = await callProxy.deploy(etherManagerContract.address);
      await callProxyContract.deployed();
      console.log("callProxyContract deployed to:", callProxyContract.address);
    }).timeout(60000);

    it("check balance for owner", async function () {
      expect(
        await BIFIERC20Contract.balanceOf(etherManagerContract.address)
      ).to.equal(hre.ethers.utils.parseEther("1000000000"));

      expect(await DAIERC20Contract.balanceOf(owner.address)).to.equal(
        hre.ethers.utils.parseEther("10000")
      );
    }).timeout(60000);

    it("we can deposit", async function () {
      await DAIERC20Contract.approve(
        tokenProxyContract.address,
        hre.ethers.utils.parseEther("100")
      );
      const depositTX = await tokenProxyContract.deposit(
        hre.ethers.utils.parseEther("100"),
        false
      );
      await depositTX.wait();
    }).timeout(60000);
  });
});

**Comment by saeedalipoorcom** [comment]
i make _applyInterest(userAddr) UN-comment  and marked below code as comment  

        /* calculate interest amount and params by call Interest Model */
        // (
        //     depositNegativeFlag,
        //     deltaDepositAmount,
        //     globalDepositEXR,
        //     borrowNegativeFlag,
        //     deltaBorrowAmount,
        //     globalBorrowEXR
        // ) = interestModelInstance.getInterestAmount(
        //     address(handlerDataStorage),
        //     userAddr,
        //     false
        // );

in _updateInterestAmount function and now it work with flag as false !

**Comment by 0xsuren** [comment]
> i deployed contracts in fork from mainnet and use this code's to make deposit ,
> 
> i use this code's in my test file to make deposit in deployed contracts ,
> 
> ```
>   await DAIERC20Contract.approve(
>     tokenProxyContract.address,
>     hre.ethers.utils.parseEther("100")
>   );
>   const depositTX = await tokenProxyContract.deposit(
>     hre.ethers.utils.parseEther("100"),
>     false
>   );
>   await depositTX.wait();
> ```
> 
> but i get error from _applyInterest(userAddr); in tokenHandler deposit function , because when i make it comment , deposit is ok . and when i pass flag as true , deposit work !
> 
> my deployment is :
> 
> const hre = require("hardhat"); const { expect } = require("chai");
> 
> describe("", async () => { let DAIOracleContract; let oracleProxyContract; let DAItokenSIContract; let DAIERC20Contract; let BIFIERC20Contract;
> 
> let managerDataStorageContract; let etherManagerContract; let etherLiquidationManagerContract; let marketHandlerDataStorageContract; let interestModelContract;
> 
> let tokenProxyContract; let DAImarketSIHandlerDataStorageContract; let DAItokenHandlerContract;
> 
> let callProxyContract;
> 
> let owner;
> 
> describe("BiFiX Deploy And Test", function () { it("deploy contracts", async function () { [owner] = await hre.ethers.getSigners();
> 
> ```
>   // deploy dai oracle
>   const observerOracle = await hre.ethers.getContractFactory(
>     "observerOracle"
>   );
>   DAIOracleContract = await observerOracle.deploy(100000000);
>   await DAIOracleContract.deployed();
>   console.log("DAIOracleContract deployed to:", DAIOracleContract.address);
> 
>   // deploy oracle proxy
>   const oracleProxy = await hre.ethers.getContractFactory("oracleProxy");
>   oracleProxyContract = await oracleProxy.deploy(DAIOracleContract.address);
>   await oracleProxyContract.deployed();
>   console.log(
>     "oracleProxyContract deployed to:",
>     oracleProxyContract.address
>   );
> 
>   // deploy daiSI from contracts/marketHandler/tokenSI.sol
>   const tokenSI = await hre.ethers.getContractFactory("tokenSI");
>   DAItokenSIContract = await tokenSI.deploy();
>   await DAItokenSIContract.deployed();
>   console.log(
>     "DAItokenSIContract deployed to:",
>     DAItokenSIContract.address
>   );
> 
>   // deploy erc20 dai from /tokenStandard/openzeppelinERC20.sol
>   const DAIERC20 = await hre.ethers.getContractFactory(
>     "openzeppelinERC20dai"
>   );
>   DAIERC20Contract = await DAIERC20.deploy("dai", "DAI", 18);
>   await DAIERC20Contract.deployed();
>   console.log("DAIERC20Contract deployed to:", DAIERC20Contract.address);
> 
>   // deploy erc20 BIFI from /tokenStandard/openzeppelinERC20.sol
>   const BIFIERC20 = await hre.ethers.getContractFactory(
>     "openzeppelinERC20"
>   );
>   BIFIERC20Contract = await BIFIERC20.deploy("BIFI", "BIFI", 18);
>   await BIFIERC20Contract.deployed();
>   console.log("BIFIERC20Contract deployed to:", BIFIERC20Contract.address);
> 
>   // deploy ManagerDataStorage from contracts/marketManager/managerDataStorage/managerDataStorage.sol
>   const managerDataStorage = await hre.ethers.getContractFactory(
>     "managerDataStorage"
>   );
>   managerDataStorageContract = await managerDataStorage.deploy();
>   await managerDataStorageContract.deployed();
>   console.log(
>     "managerDataStorageContract deployed to:",
>     managerDataStorageContract.address
>   );
> 
>   // deploy Token manager or manager from contracts/marketManager/tokenManager.sol
>   const etherManager = await hre.ethers.getContractFactory("etherManager");
>   etherManagerContract = await etherManager.deploy(
>     managerDataStorageContract.address,
>     oracleProxyContract.address,
>     "0x6d3A0d57Aa65fe133802c48F659521F7693fa477",
>     BIFIERC20Contract.address
>   );
>   await etherManagerContract.deployed();
>   console.log(
>     "etherManagerContract deployed to:",
>     etherManagerContract.address
>   );
> 
>   // change manager address in managerDataStorage
>   await managerDataStorageContract.setManagerAddr(
>     etherManagerContract.address
>   );
> 
>   // transfer 1000000000 BIFI to etherManagerContract
>   await BIFIERC20Contract.transfer(
>     etherManagerContract.address,
>     hre.ethers.utils.parseEther("1000000000")
>   );
> 
>   // transfer 1000000000 DAI to user
>   await DAIERC20Contract.transfer(
>     owner.address,
>     hre.ethers.utils.parseEther("1000")
>   );
> 
>   // deploy etherLiquidationManager from /contracts/marketManager/liquidationManager.sol
>   const etherLiquidationManager = await hre.ethers.getContractFactory(
>     "etherLiquidationManager"
>   );
>   etherLiquidationManagerContract = await etherLiquidationManager.deploy(
>     etherManagerContract.address
>   );
>   await etherLiquidationManagerContract.deployed();
>   console.log(
>     "etherLiquidationManagerContract deployed to:",
>     etherLiquidationManagerContract.address
>   );
> 
>   // set etherLiquidationManager address in etherManagerContract
>   await etherManagerContract.setLiquidationManager(
>     etherLiquidationManagerContract.address
>   );
> 
>   // MarketHandlerDataStorage
>   const borrowLimit = hre.ethers.utils.parseEther("0.75");
>   const martinCallLimit = hre.ethers.utils.parseEther("0.93");
>   const minimumInterestRate = 0;
>   const liquiditySensitive = hre.ethers.utils.parseEther("0.05");
> 
>   const marketHandlerDataStorage = await hre.ethers.getContractFactory(
>     "marketHandlerDataStorage"
>   );
>   marketHandlerDataStorageContract = await marketHandlerDataStorage.deploy(
>     borrowLimit,
>     martinCallLimit,
>     minimumInterestRate,
>     liquiditySensitive
>   );
>   await marketHandlerDataStorageContract.deployed();
>   console.log(
>     "marketHandlerDataStorageContract deployed to:",
>     marketHandlerDataStorageContract.address
>   );
> 
>   // interestModel
>   const interestModel = await hre.ethers.getContractFactory(
>     "interestModel"
>   );
>   interestModelContract = await interestModel.deploy(
>     hre.ethers.utils.parseEther("0.025"),
>     hre.ethers.utils.parseEther("0.8"),
>     hre.ethers.utils.parseEther("0.1"),
>     hre.ethers.utils.parseEther("0.18"),
>     hre.ethers.utils.parseEther("0.825")
>   );
>   await interestModelContract.deployed();
>   console.log(
>     "interestModelContract deployed to:",
>     interestModelContract.address
>   );
> 
>   // handlerProxy
>   const tokenProxy = await hre.ethers.getContractFactory("tokenProxy");
>   tokenProxyContract = await tokenProxy.deploy();
>   await tokenProxyContract.deployed();
>   console.log(
>     "tokenProxyContract deployed to:",
>     tokenProxyContract.address
>   );
> 
>   // DAI si DataStorage
>   const marketSIHandlerDataStorage = await hre.ethers.getContractFactory(
>     "marketSIHandlerDataStorage"
>   );
>   DAImarketSIHandlerDataStorageContract =
>     await marketSIHandlerDataStorage.deploy(tokenProxyContract.address);
>   await DAImarketSIHandlerDataStorageContract.deployed();
>   console.log(
>     "DAImarketSIHandlerDataStorageContract deployed to:",
>     DAImarketSIHandlerDataStorageContract.address
>   );
> 
>   // DAI Handler
>   const tokenHandler = await hre.ethers.getContractFactory("tokenHandler");
>   DAItokenHandlerContract = await tokenHandler.deploy();
>   await DAItokenHandlerContract.deployed();
>   console.log(
>     "DAItokenHandlerContract deployed to:",
>     DAItokenHandlerContract.address
>   );
> 
>   // const daiBorrowLimit = hre.ethers.utils.parseEther("0.75");
>   await etherManagerContract.handlerRegister(2, tokenProxyContract.address);
>   await marketHandlerDataStorageContract.setTokenHandler(
>     tokenProxyContract.address,
>     interestModelContract.address
>   );
>   await tokenProxyContract.initialize(
>     2,
>     DAItokenHandlerContract.address,
>     etherManagerContract.address,
>     interestModelContract.address,
>     marketHandlerDataStorageContract.address,
>     DAIERC20Contract.address,
>     "DAI",
>     DAItokenSIContract.address,
>     DAImarketSIHandlerDataStorageContract.address
>   );
> 
>   await marketHandlerDataStorageContract.setLimitOfAction(
>     hre.ethers.utils.parseEther("100000")
>   );
>   await marketHandlerDataStorageContract.setLiquidityLimit(
>     hre.ethers.utils.parseEther("1")
>   );
> 
>   const ABI = [
>     "function setUnderlyingTokenDecimal(uint256 _underlyingTokenDecimal)",
>   ];
>   const iface = new hre.ethers.utils.Interface(ABI);
>   const callBytes = iface.encodeFunctionData("setUnderlyingTokenDecimal", [
>     (10 ** 18).toString(),
>   ]);
> 
>   await tokenProxyContract.handlerViewProxy(callBytes);
> 
>   // CallProxy
>   const callProxy = await hre.ethers.getContractFactory(
>     "callProxyManagerCallProxyHandlerCallProxyMarketCallProxyUserCallProxySISafeMath"
>   );
>   callProxyContract = await callProxy.deploy(etherManagerContract.address);
>   await callProxyContract.deployed();
>   console.log("callProxyContract deployed to:", callProxyContract.address);
> }).timeout(60000);
> 
> it("check balance for owner", async function () {
>   expect(
>     await BIFIERC20Contract.balanceOf(etherManagerContract.address)
>   ).to.equal(hre.ethers.utils.parseEther("1000000000"));
> 
>   expect(await DAIERC20Contract.balanceOf(owner.address)).to.equal(
>     hre.ethers.utils.parseEther("10000")
>   );
> }).timeout(60000);
> 
> it("we can deposit", async function () {
>   await DAIERC20Contract.approve(
>     tokenProxyContract.address,
>     hre.ethers.utils.parseEther("100")
>   );
>   const depositTX = await tokenProxyContract.deposit(
>     hre.ethers.utils.parseEther("100"),
>     false
>   );
>   await depositTX.wait();
> }).timeout(60000);
> ```
> 
> }); });

fixed
